apiVersion: apps/v1
kind: Deployment
metadata:
    name: health-deployment
spec:
    replicas: 2
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
    selector:
       matchLabels:
          app: health-app
    template:
       metadata:
          labels:
             app: health-app
       spec:
          containers:
          - name: health
            image: mariegiselle8/health:dev
            ports:
              - name: web 
                containerPort: 8000
            livenessProbe:
              httpGet:
                path: /health
                port: 8000
              initialDelaySeconds: 15
              periodSeconds: 3
            readinessProbe:
              httpGet:
                path: /health
                port: 8000
              initialDelaySeconds: 15
              periodSeconds: 10